[project]
name = "polars-cache"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=8.32.0",
    "polars>=1.22.0",
    "pytest>=8.3.4",
    "rich>=13.9.4",
]
